version: 2
updates:
  # INTERNAL
  - package-ecosystem: npm
    directories:
      - '/**/*'
    schedule:
      interval: daily
    allow:
      - dependency-name: '@arbitrum/*'
      - dependency-name: '@offchainlabs/*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  # EXTERNAL
  - package-ecosystem: npm
    directories:
      - '/**/*'
    schedule:
      interval: daily
    ignore:
      - dependency-name: '@arbitrum/*'
      - dependency-name: '@offchainlabs/*'
    open-pull-requests-limit: 0 # enforces security-only PRs
