version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    versioning-strategy: increase
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
  - package-ecosystem: npm
    directories:
      - '/examples/*'
    schedule:
      interval: daily
    versioning-strategy: increase
    groups:
      # Group all updates for examples together
      examples:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
