version: 2
updates:
  - package-ecosystem: npm
    directories: ["**/*"]
    schedule: { interval: daily }
    versioning-strategy: increase
    ignore:
      - dependency-name: "@arbitrum/*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "@offchainlabs/*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
