version: 2
updates:
  # INTERNAL
  - package-ecosystem: npm
    directories:
      - '/**/*'
    schedule:
      interval: daily
    allow:
      - dependency-name: '@arbitrum/*'
      - dependency-name: '@offchainlabs/*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    groups:
      internal-major-minor:
        patterns: ['@arbitrum/*', '@offchainlabs/*']
        update-types:
          - 'major'
          - 'minor'

  # EXTERNAL
  - package-ecosystem: npm
    directories:
      - '/**/*'
    schedule:
      interval: daily
    ignore:
      - dependency-name: '@arbitrum/*'
      - dependency-name: '@offchainlabs/*'
    open-pull-requests-limit: 0
    groups:
      external-security:
        applies-to: security-updates
        exclude-patterns: ['@arbitrum/*', '@offchainlabs/*']
