version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '**/*'
    schedule:
      interval: daily
    versioning-strategy: increase
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
